name: "Vercel Set Environment Variables"
description: "A GitHub Action that ensures certain environment variables are set in Vercel"
author: "Derek Kershner"
inputs:
  token:
    required: true
    description: "Vercel API Token"
  teamId:
    required: false
    description: "Vercel API Team ID - used to target a Team or Organization, default is personal"
  projectName:
    required: true
    description: "The name of the project in Vercel"
  envVariableKeys:
    required: true
    description: "A comma delimited list of environment variable keys. This must be accompanied by a matching env variable and ones prefixed with TARGET_ and TYPE_. These match target and type in Vercel."
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: anchor
  color: gray-dark
